apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-api
  namespace: ad-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-api
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server-api
      name: server-api
    spec:
      containers:
        - image: hub.isjike.com/geek-app/server-api:<BUILD_TAG>
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "python app.py" ]
          imagePullPolicy: IfNotPresent
          name: server-api
          env:
            - name: server_api_env
              value: "pro"
          ports:
            - name: work
              containerPort: 8000
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      imagePullSecrets:
      - name: aliyun-hub
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
          name: timezone

---
apiVersion: v1
kind: Service
metadata:
  name: server-api
  namespace: ad-pro
  labels:
    srv: server-api
spec:
  type: NodePort
  ports:
    - name: work
      targetPort: 8000
      port: 8000
      protocol: TCP
      nodePort: 31097
  selector:
    app: server-api