# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services.protobuf import api_pb2 as api__pb2


class ScreenAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ad_list = channel.unary_unary(
            '/ScreenAPI/ad_list',
            request_serializer=api__pb2.ScreenAdListRequest.SerializeToString,
            response_deserializer=api__pb2.ScreenAdListReply.FromString,
        )
        self.ad_play = channel.unary_unary(
            '/ScreenAPI/ad_play',
            request_serializer=api__pb2.ScreenAdPlayRequest.SerializeToString,
            response_deserializer=api__pb2.ScreenAdPlayReply.FromString,
        )


class ScreenAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ad_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ad_play(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScreenAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ad_list': grpc.unary_unary_rpc_method_handler(
            servicer.ad_list,
            request_deserializer=api__pb2.ScreenAdListRequest.FromString,
            response_serializer=api__pb2.ScreenAdListReply.SerializeToString,
        ),
        'ad_play': grpc.unary_unary_rpc_method_handler(
            servicer.ad_play,
            request_deserializer=api__pb2.ScreenAdPlayRequest.FromString,
            response_serializer=api__pb2.ScreenAdPlayReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ScreenAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ScreenAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ad_list(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ScreenAPI/ad_list',
                                             api__pb2.ScreenAdListRequest.SerializeToString,
                                             api__pb2.ScreenAdListReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ad_play(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ScreenAPI/ad_play',
                                             api__pb2.ScreenAdPlayRequest.SerializeToString,
                                             api__pb2.ScreenAdPlayReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ServerAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ad_list = channel.unary_unary(
            '/ServerAPI/ad_list',
            request_serializer=api__pb2.ServerAdListRequest.SerializeToString,
            response_deserializer=api__pb2.ServerAdListReply.FromString,
        )
        self.ad_screens = channel.unary_unary(
            '/ServerAPI/ad_screens',
            request_serializer=api__pb2.ServerAdScreensRequest.SerializeToString,
            response_deserializer=api__pb2.ServerAdScreensReply.FromString,
        )
        self.review_list = channel.unary_unary(
            '/ServerAPI/review_list',
            request_serializer=api__pb2.ServerReviewListRequest.SerializeToString,
            response_deserializer=api__pb2.ServerReviewListReply.FromString,
        )


class ServerAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ad_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ad_screens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def review_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ad_list': grpc.unary_unary_rpc_method_handler(
            servicer.ad_list,
            request_deserializer=api__pb2.ServerAdListRequest.FromString,
            response_serializer=api__pb2.ServerAdListReply.SerializeToString,
        ),
        'ad_screens': grpc.unary_unary_rpc_method_handler(
            servicer.ad_screens,
            request_deserializer=api__pb2.ServerAdScreensRequest.FromString,
            response_serializer=api__pb2.ServerAdScreensReply.SerializeToString,
        ),
        'review_list': grpc.unary_unary_rpc_method_handler(
            servicer.review_list,
            request_deserializer=api__pb2.ServerReviewListRequest.FromString,
            response_serializer=api__pb2.ServerReviewListReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ServerAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ServerAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ad_list(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerAPI/ad_list',
                                             api__pb2.ServerAdListRequest.SerializeToString,
                                             api__pb2.ServerAdListReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ad_screens(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerAPI/ad_screens',
                                             api__pb2.ServerAdScreensRequest.SerializeToString,
                                             api__pb2.ServerAdScreensReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def review_list(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerAPI/review_list',
                                             api__pb2.ServerReviewListRequest.SerializeToString,
                                             api__pb2.ServerReviewListReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
